import { faker } from "@faker-js/faker"

const UserData = [
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.datatype.array({ min: 5, max: 10 }),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
    {
        id: faker.string.uuid(),
        photo: {
            name: faker.system.fileName(),
            url : faker.image.url(),
        },
        firstName: faker.person.firstName(),
        lastName: faker.person.lastName(),
        email: faker.internet.email(),
        description: faker.commerce.productDescription(), // 'Andy shoes are designed to keeping...',
        password: faker.internet.password({ length: 20, memorable: true }), // 'lawetimufozujosodedi'
        facebook: faker.image.url(),
        twitter: faker.image.url(),
        linkedin: faker.image.url(),
        key: faker.string.sample(10),
        secretKey: faker.string.sample(10),
        publicKey: faker.string.sample(10),
        phone: faker.phone.number(),
        date: faker.date.birthdate(),
        sex: faker.person.sexType(),
        courses: faker.helpers.arrayElement(['free', 'basic', 'business']),
    },
]

export default UserData